# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connect_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connect_form(object):
    def setupUi(self, Connect_form):
        Connect_form.setObjectName("Connect_form")
        Connect_form.resize(492, 406)
        self.IP_address_label = QtWidgets.QLabel(Connect_form)
        self.IP_address_label.setGeometry(QtCore.QRect(90, 21, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.IP_address_label.setFont(font)
        self.IP_address_label.setObjectName("IP_address_label")
        self.IP_address_textbox = QtWidgets.QLineEdit(Connect_form)
        self.IP_address_textbox.setGeometry(QtCore.QRect(230, 20, 181, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IP_address_textbox.setFont(font)
        self.IP_address_textbox.setText("")
        self.IP_address_textbox.setObjectName("IP_address_textbox")
        self.Login_texbox = QtWidgets.QLineEdit(Connect_form)
        self.Login_texbox.setGeometry(QtCore.QRect(227, 70, 181, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Login_texbox.setFont(font)
        self.Login_texbox.setObjectName("Login_texbox")
        self.Login_label = QtWidgets.QLabel(Connect_form)
        self.Login_label.setGeometry(QtCore.QRect(90, 70, 45, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Login_label.setFont(font)
        self.Login_label.setObjectName("Login_label")
        self.Pass_label = QtWidgets.QLabel(Connect_form)
        self.Pass_label.setGeometry(QtCore.QRect(90, 120, 78, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Pass_label.setFont(font)
        self.Pass_label.setObjectName("Pass_label")
        self.DB_name_label = QtWidgets.QLabel(Connect_form)
        self.DB_name_label.setGeometry(QtCore.QRect(90, 170, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DB_name_label.setFont(font)
        self.DB_name_label.setObjectName("DB_name_label")
        self.DB_name_textbox = QtWidgets.QLineEdit(Connect_form)
        self.DB_name_textbox.setGeometry(QtCore.QRect(230, 170, 181, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DB_name_textbox.setFont(font)
        self.DB_name_textbox.setObjectName("DB_name_textbox")
        self.Pass_texxtbox = QtWidgets.QLineEdit(Connect_form)
        self.Pass_texxtbox.setGeometry(QtCore.QRect(230, 120, 181, 29))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Pass_texxtbox.setFont(font)
        self.Pass_texxtbox.setObjectName("Pass_texxtbox")
        self.Connect_button = QtWidgets.QPushButton(Connect_form)
        self.Connect_button.setGeometry(QtCore.QRect(10, 280, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Connect_button.setFont(font)
        self.Connect_button.setObjectName("Connect_button")

        self.retranslateUi(Connect_form)
        QtCore.QMetaObject.connectSlotsByName(Connect_form)

    def retranslateUi(self, Connect_form):
        _translate = QtCore.QCoreApplication.translate
        Connect_form.setWindowTitle(_translate("Connect_form", "Connect to DB"))
        self.IP_address_label.setText(_translate("Connect_form", "IP address"))
        self.Login_label.setText(_translate("Connect_form", "Login"))
        self.Pass_label.setText(_translate("Connect_form", "Password"))
        self.DB_name_label.setText(_translate("Connect_form", "DataBase name"))
        self.Connect_button.setText(_translate("Connect_form", "Connect to DB"))
