# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Workspace.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Workspace(object):
    def setupUi(self, Workspace):
        Workspace.setObjectName("Workspace")
        Workspace.resize(465, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Workspace.sizePolicy().hasHeightForWidth())
        Workspace.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Workspace)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 256, 192))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Tables_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Tables_comboBox.setGeometry(QtCore.QRect(10, 10, 141, 22))
        self.Tables_comboBox.setObjectName("Tables_comboBox")
        Workspace.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Workspace)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReports = QtWidgets.QMenu(self.menuFile)
        self.menuReports.setObjectName("menuReports")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        Workspace.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Workspace)
        self.statusbar.setObjectName("statusbar")
        Workspace.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(Workspace)
        self.actionSave.setObjectName("actionSave")
        self.actionReport_1 = QtWidgets.QAction(Workspace)
        self.actionReport_1.setObjectName("actionReport_1")
        self.menuReports.addAction(self.actionReport_1)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Workspace)
        QtCore.QMetaObject.connectSlotsByName(Workspace)

    def retranslateUi(self, Workspace):
        _translate = QtCore.QCoreApplication.translate
        Workspace.setWindowTitle(_translate("Workspace", "Workspace"))
        self.menuFile.setTitle(_translate("Workspace", "File"))
        self.menuReports.setTitle(_translate("Workspace", "Reports"))
        self.menuAbout.setTitle(_translate("Workspace", "About"))
        self.actionSave.setText(_translate("Workspace", "Save"))
        self.actionReport_1.setText(_translate("Workspace", "Report 1"))
