# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Workspace.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report_form(object):
    def setupUi(self, Report_form):
        Report_form.setObjectName("Report_form")
        Report_form.resize(580, 497)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Report_form.sizePolicy().hasHeightForWidth())
        Report_form.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Report_form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")

        self.retranslateUi(Report_form)
        QtCore.QMetaObject.connectSlotsByName(Report_form)

    def retranslateUi(self, Report_form):
        _translate = QtCore.QCoreApplication.translate
        Report_form.setWindowTitle(_translate("Report_form", "Report_form"))